In [1]:
import numpy as np
import pandas as pd
import gc
import time
from contextlib import contextmanager
from lightgbm import LGBMClassifier
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.model_selection import KFold, StratifiedKFold
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from helper import *
warnings.simplefilter(action='ignore', category=FutureWarning)

/home/lizihaoleo/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [2]:
@contextmanager
def timer(title):
    t0 = time.time()
    yield
    print("{} - done in {:.0f}s".format(title, time.time() - t0))
    
# One-hot encoding for categorical columns with get_dummies
def one_hot_encoder(df, nan_as_category = True):
    original_columns = list(df.columns)
    categorical_columns = [col for col in df.columns if df[col].dtype == 'object']
    df = pd.get_dummies(df, columns= categorical_columns, dummy_na= nan_as_category)
    new_columns = [c for c in df.columns if c not in original_columns]
    return df, new_columns

In [3]:
# Preprocess application_train.csv and application_test.csv
def application_train_test(num_rows = None, nan_as_category = False):
    # Read data and merge
    df = pd.read_csv('./input/application_train.csv', nrows= num_rows)
    test_df = pd.read_csv('./input/application_test.csv', nrows= num_rows)
    print("Train samples: {}, test samples: {}".format(len(df), len(test_df)))
#     df, test_df = standard_preprocess(df, test_df)
    df = df.append(test_df).reset_index()
#     Optional: Remove 4 applications with XNA CODE_GENDER (train set)
#     df = df[df['CODE_GENDER'] != 'XNA']
    
    # Categorical features with Binary encode (0 or 1; two categories)
    for bin_feature in ['CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY']:
        df[bin_feature], uniques = pd.factorize(df[bin_feature])
    # Categorical features with One-Hot encode
    df, cat_cols = one_hot_encoder(df, nan_as_category)
    
    # NaN values for DAYS_EMPLOYED: 365.243 -> nan
    df['DAYS_EMPLOYED'].replace(365243, np.nan, inplace= True)
    # Some simple new features (percentages)
    df['DAYS_EMPLOYED_PERC'] = df['DAYS_EMPLOYED'] / df['DAYS_BIRTH']
    df['INCOME_CREDIT_PERC'] = df['AMT_INCOME_TOTAL'] / df['AMT_CREDIT']
    df['INCOME_PER_PERSON'] = df['AMT_INCOME_TOTAL'] / df['CNT_FAM_MEMBERS']
    df['ANNUITY_INCOME_PERC'] = df['AMT_ANNUITY'] / df['AMT_INCOME_TOTAL']
    df['PAYMENT_RATE'] = df['AMT_ANNUITY'] / df['AMT_CREDIT']
    print('df shape: ', df.shape)
    del test_df
    gc.collect()
    return df

In [4]:
with timer("Preprocess application_train.csv and application_test.csv"):
    df = application_train_test()

Train samples: 307511, test samples: 48744
df shape:  (356255, 248)
Preprocess application_train.csv and application_test.csv - done in 6s

In [5]:
# Preprocess bureau.csv and bureau_balance.csv
def bureau_and_balance(num_rows = None, nan_as_category = True):
    bureau = pd.read_csv('./input/bureau.csv', nrows = num_rows)
    bb = pd.read_csv('./input/bureau_balance.csv', nrows = num_rows)
    bb, bb_cat = one_hot_encoder(bb, nan_as_category)
    bureau, bureau_cat = one_hot_encoder(bureau, nan_as_category)
    
    # Bureau balance: Perform aggregations and merge with bureau.csv
    bb_aggregations = {'MONTHS_BALANCE': ['min', 'max', 'size']}
    for col in bb_cat:
        bb_aggregations[col] = ['mean']
    bb_agg = bb.groupby('SK_ID_BUREAU').agg(bb_aggregations)
    bb_agg.columns = pd.Index([e[0] + "_" + e[1].upper() for e in bb_agg.columns.tolist()])
    bureau = bureau.join(bb_agg, how='left', on='SK_ID_BUREAU')
    bureau.drop(['SK_ID_BUREAU'], axis=1, inplace= True)
    del bb, bb_agg
    gc.collect()
    
    # Bureau and bureau_balance numeric features
    num_aggregations = {
        'DAYS_CREDIT': ['min', 'max', 'mean', 'var'],
        'DAYS_CREDIT_ENDDATE': ['min', 'max', 'mean'],
        'DAYS_CREDIT_UPDATE': ['mean'],
        'CREDIT_DAY_OVERDUE': ['max', 'mean'],
        'AMT_CREDIT_MAX_OVERDUE': ['mean'],
        'AMT_CREDIT_SUM': ['max', 'mean', 'sum'],
        'AMT_CREDIT_SUM_DEBT': ['max', 'mean', 'sum'],
        'AMT_CREDIT_SUM_OVERDUE': ['mean'],
        'AMT_CREDIT_SUM_LIMIT': ['mean', 'sum'],
        'AMT_ANNUITY': ['max', 'mean'],
        'CNT_CREDIT_PROLONG': ['sum'],
        'MONTHS_BALANCE_MIN': ['min'],
        'MONTHS_BALANCE_MAX': ['max'],
        'MONTHS_BALANCE_SIZE': ['mean', 'sum']
    }
    # Bureau and bureau_balance categorical features
    cat_aggregations = {}
    for cat in bureau_cat: cat_aggregations[cat] = ['mean']
    for cat in bb_cat: cat_aggregations[cat + "_MEAN"] = ['mean']
    
    bureau_agg = bureau.groupby('SK_ID_CURR').agg({**num_aggregations, **cat_aggregations})
    bureau_agg.columns = pd.Index(['BURO_' + e[0] + "_" + e[1].upper() for e in bureau_agg.columns.tolist()])
    # Bureau: Active credits - using only numerical aggregations
    active = bureau[bureau['CREDIT_ACTIVE_Active'] == 1]
    active_agg = active.groupby('SK_ID_CURR').agg(num_aggregations)
    active_agg.columns = pd.Index(['ACTIVE_' + e[0] + "_" + e[1].upper() for e in active_agg.columns.tolist()])
    bureau_agg = bureau_agg.join(active_agg, how='left', on='SK_ID_CURR')
    del active, active_agg
    gc.collect()
    # Bureau: Closed credits - using only numerical aggregations
    closed = bureau[bureau['CREDIT_ACTIVE_Closed'] == 1]
    closed_agg = closed.groupby('SK_ID_CURR').agg(num_aggregations)
    closed_agg.columns = pd.Index(['CLOSED_' + e[0] + "_" + e[1].upper() for e in closed_agg.columns.tolist()])
    bureau_agg = bureau_agg.join(closed_agg, how='left', on='SK_ID_CURR')
    del closed, closed_agg, bureau
    gc.collect()
    return bureau_agg

In [6]:
with timer("Preprocess bureau.csv and bureau_balance.csv"):
    bureau = bureau_and_balance()
    print("Bureau df shape:", bureau.shape)
    df = df.join(bureau, how='left', on='SK_ID_CURR')
    del bureau
    gc.collect()

Bureau df shape: (305811, 116)
Preprocess bureau.csv and bureau_balance.csv - done in 24s

In [7]:
# Preprocess previous_applications.csv
def previous_applications(num_rows = None, nan_as_category = True):
    prev_original = pd.read_csv('./input/previous_application.csv', nrows = num_rows)
    prev, cat_cols = one_hot_encoder(prev_original, nan_as_category= True)
    # Days 365.243 values -> nan
    prev['DAYS_FIRST_DRAWING'].replace(365243, np.nan, inplace= True)
    prev['DAYS_FIRST_DUE'].replace(365243, np.nan, inplace= True)
    prev['DAYS_LAST_DUE_1ST_VERSION'].replace(365243, np.nan, inplace= True)
    prev['DAYS_LAST_DUE'].replace(365243, np.nan, inplace= True)
    prev['DAYS_TERMINATION'].replace(365243, np.nan, inplace= True)
    # Add feature: value ask / value received percentage
    prev['APP_CREDIT_PERC'] = prev['AMT_APPLICATION'] / prev['AMT_CREDIT']

    # Previous applications numeric features
    num_aggregations = {
        'AMT_ANNUITY': ['min', 'max', 'mean','median','std'],
        'AMT_APPLICATION': ['min', 'max', 'mean','median','std'],
        'AMT_CREDIT': ['min', 'max', 'mean','median','std'],
        'APP_CREDIT_PERC': ['min', 'max', 'mean', 'var','median','std'],
        'AMT_DOWN_PAYMENT': ['min', 'max', 'mean','median','std'],
        'AMT_GOODS_PRICE': ['min', 'max', 'mean','median','std'],
        'HOUR_APPR_PROCESS_START': ['min', 'max', 'mean','median','std'],
        'RATE_DOWN_PAYMENT': ['min', 'max', 'mean','median','std'],
        'DAYS_DECISION': ['min', 'max', 'mean','median','std'],
        'CNT_PAYMENT': ['mean', 'sum'],
    }
    # Previous applications categorical features
    cat_aggregations = {}
    for cat in cat_cols:
        cat_aggregations[cat] = ['mean','sum']

    prev_agg = prev.groupby('SK_ID_CURR').agg({**num_aggregations, **cat_aggregations})

    prev_agg.columns = pd.Index(['PREV_' + e[0] + "_" + e[1].upper() for e in prev_agg.columns.tolist()])

    prev_cat = count_categorical(prev_original, group_var = 'SK_ID_CURR', df_name = 'PREV')

    # Add feature: approved rate
    prev_cat['APR_RATE'] = prev_cat['PREV_NAME_CONTRACT_STATUS_Approved_count'] / (prev_cat['PREV_NAME_CONTRACT_STATUS_Approved_count'] + prev_cat['PREV_NAME_CONTRACT_STATUS_Refused_count'])

    prev_apr_rate_df = prev_cat[['APR_RATE']]

    # Previous Applications: Approved Applications - only numerical features
    approved = prev[prev['NAME_CONTRACT_STATUS_Approved'] == 1]
    approved_agg = approved.groupby('SK_ID_CURR').agg(num_aggregations)
    approved_agg.columns = pd.Index(['APPROVED_' + e[0] + "_" + e[1].upper() for e in approved_agg.columns.tolist()])
    prev_agg = prev_agg.join(approved_agg, how='left', on='SK_ID_CURR')
    # Previous Applications: Refused Applications - only numerical features
    refused = prev[prev['NAME_CONTRACT_STATUS_Refused'] == 1]
    refused_agg = refused.groupby('SK_ID_CURR').agg(num_aggregations)
    refused_agg.columns = pd.Index(['REFUSED_' + e[0] + "_" + e[1].upper() for e in refused_agg.columns.tolist()])
    prev_agg = prev_agg.join(refused_agg, how='left', on='SK_ID_CURR')

    prev_agg = prev_agg.join(prev_apr_rate_df, how='left', on='SK_ID_CURR')

    del refused, refused_agg, approved, approved_agg, prev, prev_cat, prev_apr_rate_df
    gc.collect()
    
    return prev_agg

In [8]:
with timer("Process previous_applications"):
    prev = previous_applications()
    print("Previous applications df shape:", prev.shape)
    df = df.join(prev, how='left', on='SK_ID_CURR')
    del prev
    gc.collect()

Previous applications df shape: (338857, 463)
Process previous_applications - done in 67s

In [9]:
# Preprocess POS_CASH_balance.csv
def pos_cash(num_rows = None, nan_as_category = True):
    pos = pd.read_csv('./input/POS_CASH_balance.csv', nrows = num_rows)
    pos, cat_cols = one_hot_encoder(pos, nan_as_category= True)
    # Features
    aggregations = {
        'MONTHS_BALANCE': ['max', 'mean', 'size'],
        'SK_DPD': ['max', 'mean'],
        'SK_DPD_DEF': ['max', 'mean']
    }
    for cat in cat_cols:
        aggregations[cat] = ['mean']
    
    pos_agg = pos.groupby('SK_ID_CURR').agg(aggregations)
    pos_agg.columns = pd.Index(['POS_' + e[0] + "_" + e[1].upper() for e in pos_agg.columns.tolist()])
    # Count pos cash accounts
    pos_agg['POS_COUNT'] = pos.groupby('SK_ID_CURR').size()
    del pos
    gc.collect()
    return pos_agg

In [10]:
    with timer("Process POS-CASH balance"):
        pos = pos_cash()
        print("Pos-cash balance df shape:", pos.shape)
        df = df.join(pos, how='left', on='SK_ID_CURR')
        del pos
        gc.collect()

Pos-cash balance df shape: (337252, 18)
Process POS-CASH balance - done in 14s

In [11]:
# Preprocess installments_payments.csv
def installments_payments(num_rows = None, nan_as_category = True):
    ins = pd.read_csv('./input/installments_payments.csv', nrows = num_rows)
    ins, cat_cols = one_hot_encoder(ins, nan_as_category= True)
    # Percentage and difference paid in each installment (amount paid and installment value)
    ins['PAYMENT_PERC'] = ins['AMT_PAYMENT'] / ins['AMT_INSTALMENT']
    ins['PAYMENT_DIFF'] = ins['AMT_INSTALMENT'] - ins['AMT_PAYMENT']
    # Days past due and days before due (no negative values)
    ins['DPD'] = ins['DAYS_ENTRY_PAYMENT'] - ins['DAYS_INSTALMENT']
    ins['DBD'] = ins['DAYS_INSTALMENT'] - ins['DAYS_ENTRY_PAYMENT']
    ins['DPD'] = ins['DPD'].apply(lambda x: x if x > 0 else 0)
    ins['DBD'] = ins['DBD'].apply(lambda x: x if x > 0 else 0)
    # Features: Perform aggregations
    aggregations = {
        'NUM_INSTALMENT_VERSION': ['nunique'],
        'DPD': ['max', 'mean', 'sum'],
        'DBD': ['max', 'mean', 'sum'],
        'PAYMENT_PERC': ['max', 'mean', 'sum', 'var'],
        'PAYMENT_DIFF': ['max', 'mean', 'sum', 'var'],
        'AMT_INSTALMENT': ['max', 'mean', 'sum'],
        'AMT_PAYMENT': ['min', 'max', 'mean', 'sum'],
        'DAYS_ENTRY_PAYMENT': ['max', 'mean', 'sum']
    }
    for cat in cat_cols:
        aggregations[cat] = ['mean']
    ins_agg = ins.groupby('SK_ID_CURR').agg(aggregations)
    ins_agg.columns = pd.Index(['INSTAL_' + e[0] + "_" + e[1].upper() for e in ins_agg.columns.tolist()])
    # Count installments accounts
    ins_agg['INSTAL_COUNT'] = ins.groupby('SK_ID_CURR').size()
    del ins
    gc.collect()
    return ins_agg

In [12]:
with timer("Process installments payments"):
    ins = installments_payments()
    print("Installments payments df shape:", ins.shape)
    df = df.join(ins, how='left', on='SK_ID_CURR')
    del ins
    gc.collect()

Installments payments df shape: (339587, 26)
Process installments payments - done in 31s

In [13]:
# Preprocess credit_card_balance.csv
def credit_card_balance(num_rows = None, nan_as_category = True):
    cc = pd.read_csv('./input/credit_card_balance.csv', nrows = num_rows)
    cc, cat_cols = one_hot_encoder(cc, nan_as_category= True)
    # General aggregations
    cc.drop(['SK_ID_PREV'], axis= 1, inplace = True)
    cc_agg = cc.groupby('SK_ID_CURR').agg(['min', 'max', 'mean', 'sum', 'var'])
    cc_agg.columns = pd.Index(['CC_' + e[0] + "_" + e[1].upper() for e in cc_agg.columns.tolist()])
    # Count credit card lines
    cc_agg['CC_COUNT'] = cc.groupby('SK_ID_CURR').size()
    del cc
    gc.collect()
    return cc_agg

In [14]:
with timer("Process credit card balance"):
    cc = credit_card_balance()
    print("Credit card balance df shape:", cc.shape)
    df = df.join(cc, how='left', on='SK_ID_CURR')
    del cc
    gc.collect()

Credit card balance df shape: (103558, 141)
Process credit card balance - done in 16s

In [15]:
df.head()

,index,AMT_ANNUITY,AMT_CREDIT,AMT_GOODS_PRICE,AMT_INCOME_TOTAL,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_WEEK,...,CC_NAME_CONTRACT_STATUS_Signed_MAX,CC_NAME_CONTRACT_STATUS_Signed_MEAN,CC_NAME_CONTRACT_STATUS_Signed_SUM,CC_NAME_CONTRACT_STATUS_Signed_VAR,CC_NAME_CONTRACT_STATUS_nan_MIN,CC_NAME_CONTRACT_STATUS_nan_MAX,CC_NAME_CONTRACT_STATUS_nan_MEAN,CC_NAME_CONTRACT_STATUS_nan_SUM,CC_NAME_CONTRACT_STATUS_nan_VAR,CC_COUNT
0,0,24700.5,406597.5,351000.0,202500.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,35698.5,1293502.5,1129500.0,270000.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,6750.0,135000.0,135000.0,67500.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,29686.5,312682.5,297000.0,135000.0,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0
4,4,21865.5,513000.0,513000.0,121500.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df = df.drop(columns='index')

In [17]:
train = df[df['TARGET'].notnull()]
test = df[df['TARGET'].isnull()].drop(columns = ['TARGET'])
submission, fi, metrics = lgb_model(train, test)

Training Data Shape:  (307511, 1009)
Testing Data Shape:  (48744, 1009)
Training until validation scores don't improve for 100 rounds.
[200]	valid's auc: 0.785423	train's auc: 0.8349
[400]	valid's auc: 0.786384	train's auc: 0.87228
Early stopping, best iteration is:
[331]	valid's auc: 0.78669	train's auc: 0.860804
Training until validation scores don't improve for 100 rounds.
[200]	valid's auc: 0.788732	train's auc: 0.833427
[400]	valid's auc: 0.790148	train's auc: 0.871237
Early stopping, best iteration is:
[420]	valid's auc: 0.790353	train's auc: 0.87443
Training until validation scores don't improve for 100 rounds.
[200]	valid's auc: 0.779166	train's auc: 0.835512
[400]	valid's auc: 0.780809	train's auc: 0.872829
Early stopping, best iteration is:
[393]	valid's auc: 0.781003	train's auc: 0.871711
Training until validation scores don't improve for 100 rounds.
[200]	valid's auc: 0.785891	train's auc: 0.834108
[400]	valid's auc: 0.786575	train's auc: 0.871769
Early stopping, best iteration is:
[348]	valid's auc: 0.787127	train's auc: 0.863372
Training until validation scores don't improve for 100 rounds.
[200]	valid's auc: 0.788168	train's auc: 0.83384
[400]	valid's auc: 0.78952	train's auc: 0.871278
Early stopping, best iteration is:
[348]	valid's auc: 0.789616	train's auc: 0.862862

In [18]:
metrics

      fold     train     valid
0        0  0.860804  0.786690
1        1  0.874430  0.790353
2        2  0.871711  0.781003
3        3  0.863372  0.787127
4        4  0.862862  0.789616
5  overall  0.866636  0.786891

In [19]:
train, test = remove_cor(train,test,threshold=.9)

Number of columns to remove:  220
Training Corrs Removed Shape:  (307511, 791)
Testing Corrs Removed Shape:  (48744, 790)

In [23]:
submission, fi, metrics = lgb_model(train, test)
metric

Training Data Shape:  (307511, 789)
Testing Data Shape:  (48744, 789)
Training until validation scores don't improve for 100 rounds.
[200]	valid's auc: 0.785923	train's auc: 0.832991
[400]	valid's auc: 0.786778	train's auc: 0.869114
Early stopping, best iteration is:
[316]	valid's auc: 0.787082	train's auc: 0.855556
Training until validation scores don't improve for 100 rounds.
[200]	valid's auc: 0.788199	train's auc: 0.831958
[400]	valid's auc: 0.789393	train's auc: 0.868719
Early stopping, best iteration is:
[339]	valid's auc: 0.789891	train's auc: 0.859017
Training until validation scores don't improve for 100 rounds.
[200]	valid's auc: 0.777419	train's auc: 0.833654
[400]	valid's auc: 0.779712	train's auc: 0.870151
Early stopping, best iteration is:
[347]	valid's auc: 0.779895	train's auc: 0.861758
Training until validation scores don't improve for 100 rounds.
[200]	valid's auc: 0.785798	train's auc: 0.832277
[400]	valid's auc: 0.786431	train's auc: 0.869001
Early stopping, best iteration is:
[302]	valid's auc: 0.786607	train's auc: 0.852515
Training until validation scores don't improve for 100 rounds.
[200]	valid's auc: 0.786563	train's auc: 0.832158
[400]	valid's auc: 0.788444	train's auc: 0.868954
Early stopping, best iteration is:
[436]	valid's auc: 0.788659	train's auc: 0.874361

NameError: name 'metric' is not defined

In [21]:
metrics

      fold     train     valid
0        0  0.855556  0.787082
1        1  0.859017  0.789891
2        2  0.861758  0.779895
3        3  0.852515  0.786607
4        4  0.874361  0.788659
5  overall  0.860641  0.786398

In [18]:
df.to_csv('./preprocessed_data/all_data_v2.csv', index = False)
del df
gc.collect()

22

In [2]:
# Read in the feature importances and sort with the most important at the top
fi = pd.read_csv('./input/spec_feature_importances_ohe.csv', index_col = 0)
fi = fi.sort_values('importance', ascending = False)
# fi.head(100)

In [4]:
top_num = 50
top = list(fi['feature'])[:top_num]

In [5]:
top.append('SK_ID_CURR')

In [6]:
del fi
gc.collect()

7

In [7]:
features = pd.read_csv('./input/feature_matrix.csv')
features.head()

,SK_ID_CURR,NAME_TYPE_SUITE,REG_REGION_NOT_LIVE_REGION,EXT_SOURCE_2,OCCUPATION_TYPE,FLAG_PHONE,AMT_INCOME_TOTAL,AMT_CREDIT,REGION_RATING_CLIENT,REG_REGION_NOT_WORK_REGION,...,MIN(previous_app.MAX(credit.MONTHS_BALANCE)),MEAN(previous_app.MEAN(installments.NUM_INSTALMENT_NUMBER)),SUM(previous_app.MAX(installments.DAYS_ENTRY_PAYMENT)),MEAN(previous_app.MAX(installments.AMT_PAYMENT)),STD(previous_app.SUM(cash.CNT_INSTALMENT)),STD(previous_app.MIN(cash.CNT_INSTALMENT)),STD(previous_app.MEAN(credit.CNT_DRAWINGS_OTHER_CURRENT)),MIN(previous_app.STD(credit.CNT_DRAWINGS_OTHER_CURRENT)),MIN(previous_app.SKEW(credit.AMT_DRAWINGS_OTHER_CURRENT)),SKEW(previous_app.SUM(credit.AMT_RECEIVABLE_PRINCIPAL))
0,100001,Unaccompanied,0,0.789654,NaN,0,135000.0,568800.0,2,0,...,NaN,2.500000,-1628.0,17397.900,0.000000,0.000000,NaN,NaN,NaN,NaN
1,100002,Unaccompanied,0,0.262949,Laborers,1,202500.0,406597.5,2,0,...,NaN,10.000000,-49.0,53093.745,0.000000,0.000000,NaN,NaN,NaN,NaN
2,100003,Family,0,0.622246,Core staff,1,270000.0,1293502.5,1,0,...,NaN,4.666667,-3190.0,210713.445,39.262648,2.624669,NaN,NaN,NaN,NaN
3,100004,Unaccompanied,0,0.555912,Laborers,1,67500.0,135000.0,2,0,...,NaN,2.000000,-727.0,10573.965,0.000000,0.000000,NaN,NaN,NaN,NaN
4,100005,Unaccompanied,0,0.291656,Low-skill Laborers,0,99000.0,222768.0,2,0,...,NaN,5.000000,-470.0,17656.245,0.000000,0.000000,NaN,NaN,NaN,NaN

In [8]:
features = pd.get_dummies(features)
features.head()

,SK_ID_CURR,REG_REGION_NOT_LIVE_REGION,EXT_SOURCE_2,FLAG_PHONE,AMT_INCOME_TOTAL,AMT_CREDIT,REGION_RATING_CLIENT,REG_REGION_NOT_WORK_REGION,CNT_FAM_MEMBERS,DAYS_BIRTH,...,MODE(previous_app.MODE(cash.NAME_CONTRACT_STATUS))_Demand,MODE(previous_app.MODE(cash.NAME_CONTRACT_STATUS))_Returned to the store,MODE(previous_app.MODE(cash.NAME_CONTRACT_STATUS))_Signed,MODE(bureau.MODE(bureau_balance.STATUS))_0,MODE(bureau.MODE(bureau_balance.STATUS))_1,MODE(bureau.MODE(bureau_balance.STATUS))_2,MODE(bureau.MODE(bureau_balance.STATUS))_3,MODE(bureau.MODE(bureau_balance.STATUS))_5,MODE(bureau.MODE(bureau_balance.STATUS))_C,MODE(bureau.MODE(bureau_balance.STATUS))_X
0,100001,0,0.789654,0,135000.0,568800.0,2,0,2.0,-19241,...,0,0,0,0,0,0,0,0,1,0
1,100002,0,0.262949,1,202500.0,406597.5,2,0,1.0,-9461,...,0,0,0,0,1,0,0,0,0,0
2,100003,0,0.622246,1,270000.0,1293502.5,1,0,2.0,-16765,...,0,0,0,0,0,0,0,0,0,0
3,100004,0,0.555912,1,67500.0,135000.0,2,0,1.0,-19046,...,0,0,0,0,0,0,0,0,0,0
4,100005,0,0.291656,0,99000.0,222768.0,2,0,2.0,-18064,...,0,0,0,1,0,0,0,0,0,0

In [9]:
features_top = features[top]
features_top.to_csv('./preprocessed_data/top.csv', index = False)

In [10]:
del features, features_top
gc.collect()

14

In [2]:
df = pd.read_csv('./preprocessed_data/all_data_v2.csv')
features_top = pd.read_csv('./preprocessed_data/top.csv')

In [3]:
print(df.shape, features_top.shape)

(356255, 957) (356255, 101)

In [4]:
features_top.head()

,EXT_SOURCE_1,EXT_SOURCE_3,EXT_SOURCE_2,DAYS_BIRTH,AMT_CREDIT,AMT_ANNUITY,DAYS_EMPLOYED,AMT_GOODS_PRICE,MAX(bureau.DAYS_CREDIT),DAYS_ID_PUBLISH,...,APARTMENTS_MODE,REGION_RATING_CLIENT_W_CITY,SUM(bureau.DAYS_CREDIT_UPDATE),MIN(previous_app.SUM(cash.SK_ID_CURR)),HOUR_APPR_PROCESS_START,MEAN(installments.NUM_INSTALMENT_VERSION),SUM(bureau.DAYS_ENDDATE_FACT),SUM(previous_app.DAYS_LAST_DUE_1ST_VERSION),MEAN(installments.AMT_PAYMENT),SK_ID_CURR
0,0.752614,0.159520,0.789654,-19241,568800.0,20560.5,-2329,450000.0,-49.0,-812,...,0.0672,2,-652.0,500005.0,18,1.250000,-3302.0,-1499.0,7312.725000,100001
1,0.083037,0.139376,0.262949,-9461,406597.5,24700.5,-637,351000.0,-103.0,-2120,...,0.0252,2,-3999.0,1900038.0,10,1.052632,-4185.0,125.0,11559.247105,100002
2,0.311267,NaN,0.622246,-16765,1293502.5,35698.5,-1188,1129500.0,-606.0,-291,...,0.0924,1,-3264.0,800024.0,11,1.040000,-3292.0,-3013.0,64754.586000,100003
3,NaN,0.729567,0.555912,-19046,135000.0,6750.0,-225,135000.0,-408.0,-2531,...,NaN,2,-1064.0,400016.0,9,1.333333,-1065.0,-694.0,7096.155000,100004
4,0.564990,0.432962,0.291656,-18064,222768.0,17370.0,-4469,180000.0,-62.0,-1623,...,NaN,2,-163.0,1100055.0,9,1.111111,-123.0,-376.0,6240.205000,100005

In [5]:
overlap_col = ['AMT_ANNUITY', 'AMT_CREDIT', 'AMT_GOODS_PRICE', 'AMT_INCOME_TOTAL',
       'APARTMENTS_MODE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_ID_PUBLISH',
       'DAYS_LAST_PHONE_CHANGE', 'DAYS_REGISTRATION', 'EXT_SOURCE_1',
       'EXT_SOURCE_2', 'EXT_SOURCE_3', 'HOUR_APPR_PROCESS_START',
       'OWN_CAR_AGE', 'REGION_POPULATION_RELATIVE',
       'REGION_RATING_CLIENT_W_CITY', 'TOTALAREA_MODE',
       'NAME_EDUCATION_TYPE_Higher education', 'NAME_FAMILY_STATUS_Married']
df = df.drop(columns=overlap_col)
print(df.shape)

(356255, 937)

In [7]:
df = df.merge(features_top, how='left', on='SK_ID_CURR')
print(df.shape)

(356255, 1037)

In [8]:
df.head()

,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_YEAR,APARTMENTS_AVG,APARTMENTS_MEDI,BASEMENTAREA_AVG,BASEMENTAREA_MEDI,...,MEAN(previous_app.SUM(cash.SK_ID_CURR)),APARTMENTS_MODE,REGION_RATING_CLIENT_W_CITY,SUM(bureau.DAYS_CREDIT_UPDATE),MIN(previous_app.SUM(cash.SK_ID_CURR)),HOUR_APPR_PROCESS_START,MEAN(installments.NUM_INSTALMENT_VERSION),SUM(bureau.DAYS_ENDDATE_FACT),SUM(previous_app.DAYS_LAST_DUE_1ST_VERSION),MEAN(installments.AMT_PAYMENT)
0,0.0,0.0,0.0,0.0,0.0,1.0,0.0247,0.0250,0.0369,0.0369,...,1.900038e+06,0.0252,2,-3999.0,1900038.0,10,1.052632,-4185.0,125.0,11559.247105
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0959,0.0968,0.0529,0.0529,...,9.333613e+05,0.0924,1,-3264.0,800024.0,11,1.040000,-3292.0,-3013.0,64754.586000
2,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,...,4.000160e+05,NaN,2,-1064.0,400016.0,9,1.333333,-1065.0,-694.0,7096.155000
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.000420e+05,NaN,2,NaN,300018.0,17,1.125000,NaN,366336.0,62947.088438
4,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,...,1.320092e+06,NaN,2,-783.0,1000070.0,11,1.166667,-783.0,-4186.0,12214.060227

In [15]:
list(df.columns)

['index',
 'AMT_REQ_CREDIT_BUREAU_DAY',
 'AMT_REQ_CREDIT_BUREAU_HOUR',
 'AMT_REQ_CREDIT_BUREAU_MON',
 'AMT_REQ_CREDIT_BUREAU_QRT',
 'AMT_REQ_CREDIT_BUREAU_WEEK',
 'AMT_REQ_CREDIT_BUREAU_YEAR',
 'APARTMENTS_AVG',
 'APARTMENTS_MEDI',
 'BASEMENTAREA_AVG',
 'BASEMENTAREA_MEDI',
 'BASEMENTAREA_MODE',
 'CNT_CHILDREN',
 'CNT_FAM_MEMBERS',
 'CODE_GENDER',
 'COMMONAREA_AVG',
 'COMMONAREA_MEDI',
 'COMMONAREA_MODE',
 'DEF_30_CNT_SOCIAL_CIRCLE',
 'DEF_60_CNT_SOCIAL_CIRCLE',
 'ELEVATORS_AVG',
 'ELEVATORS_MEDI',
 'ELEVATORS_MODE',
 'ENTRANCES_AVG',
 'ENTRANCES_MEDI',
 'ENTRANCES_MODE',
 'FLAG_CONT_MOBILE',
 'FLAG_DOCUMENT_10',
 'FLAG_DOCUMENT_11',
 'FLAG_DOCUMENT_12',
 'FLAG_DOCUMENT_13',
 'FLAG_DOCUMENT_14',
 'FLAG_DOCUMENT_15',
 'FLAG_DOCUMENT_16',
 'FLAG_DOCUMENT_17',
 'FLAG_DOCUMENT_18',
 'FLAG_DOCUMENT_19',
 'FLAG_DOCUMENT_2',
 'FLAG_DOCUMENT_20',
 'FLAG_DOCUMENT_21',
 'FLAG_DOCUMENT_3',
 'FLAG_DOCUMENT_4',
 'FLAG_DOCUMENT_5',
 'FLAG_DOCUMENT_6',
 'FLAG_DOCUMENT_7',
 'FLAG_DOCUMENT_8',
 'FLAG_DOCUMENT_9',
 'FLAG_EMAIL',
 'FLAG_EMP_PHONE',
 'FLAG_MOBIL',
 'FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'FLAG_PHONE',
 'FLAG_WORK_PHONE',
 'FLOORSMAX_AVG',
 'FLOORSMAX_MEDI',
 'FLOORSMAX_MODE',
 'FLOORSMIN_AVG',
 'FLOORSMIN_MEDI',
 'FLOORSMIN_MODE',
 'LANDAREA_AVG',
 'LANDAREA_MEDI',
 'LANDAREA_MODE',
 'LIVE_CITY_NOT_WORK_CITY',
 'LIVE_REGION_NOT_WORK_REGION',
 'LIVINGAPARTMENTS_AVG',
 'LIVINGAPARTMENTS_MEDI',
 'LIVINGAPARTMENTS_MODE',
 'LIVINGAREA_AVG',
 'LIVINGAREA_MEDI',
 'LIVINGAREA_MODE',
 'NONLIVINGAPARTMENTS_AVG',
 'NONLIVINGAPARTMENTS_MEDI',
 'NONLIVINGAPARTMENTS_MODE',
 'NONLIVINGAREA_AVG',
 'NONLIVINGAREA_MEDI',
 'NONLIVINGAREA_MODE',
 'OBS_30_CNT_SOCIAL_CIRCLE',
 'OBS_60_CNT_SOCIAL_CIRCLE',
 'REGION_RATING_CLIENT',
 'REG_CITY_NOT_LIVE_CITY',
 'REG_CITY_NOT_WORK_CITY',
 'REG_REGION_NOT_LIVE_REGION',
 'REG_REGION_NOT_WORK_REGION',
 'SK_ID_CURR',
 'TARGET',
 'YEARS_BEGINEXPLUATATION_AVG',
 'YEARS_BEGINEXPLUATATION_MEDI',
 'YEARS_BEGINEXPLUATATION_MODE',
 'YEARS_BUILD_AVG',
 'YEARS_BUILD_MEDI',
 'YEARS_BUILD_MODE',
 'EMERGENCYSTATE_MODE_No',
 'EMERGENCYSTATE_MODE_Yes',
 'FONDKAPREMONT_MODE_not specified',
 'FONDKAPREMONT_MODE_org spec account',
 'FONDKAPREMONT_MODE_reg oper account',
 'FONDKAPREMONT_MODE_reg oper spec account',
 'HOUSETYPE_MODE_block of flats',
 'HOUSETYPE_MODE_specific housing',
 'HOUSETYPE_MODE_terraced house',
 'NAME_CONTRACT_TYPE_Cash loans',
 'NAME_CONTRACT_TYPE_Revolving loans',
 'NAME_EDUCATION_TYPE_Academic degree',
 'NAME_EDUCATION_TYPE_Incomplete higher',
 'NAME_EDUCATION_TYPE_Lower secondary',
 'NAME_EDUCATION_TYPE_Secondary / secondary special',
 'NAME_FAMILY_STATUS_Civil marriage',
 'NAME_FAMILY_STATUS_Separated',
 'NAME_FAMILY_STATUS_Single / not married',
 'NAME_FAMILY_STATUS_Unknown',
 'NAME_FAMILY_STATUS_Widow',
 'NAME_HOUSING_TYPE_Co-op apartment',
 'NAME_HOUSING_TYPE_House / apartment',
 'NAME_HOUSING_TYPE_Municipal apartment',
 'NAME_HOUSING_TYPE_Office apartment',
 'NAME_HOUSING_TYPE_Rented apartment',
 'NAME_HOUSING_TYPE_With parents',
 'NAME_INCOME_TYPE_Businessman',
 'NAME_INCOME_TYPE_Commercial associate',
 'NAME_INCOME_TYPE_Maternity leave',
 'NAME_INCOME_TYPE_Pensioner',
 'NAME_INCOME_TYPE_State servant',
 'NAME_INCOME_TYPE_Student',
 'NAME_INCOME_TYPE_Unemployed',
 'NAME_INCOME_TYPE_Working',
 'NAME_TYPE_SUITE_Children',
 'NAME_TYPE_SUITE_Family',
 'NAME_TYPE_SUITE_Group of people',
 'NAME_TYPE_SUITE_Other_A',
 'NAME_TYPE_SUITE_Other_B',
 'NAME_TYPE_SUITE_Spouse, partner',
 'NAME_TYPE_SUITE_Unaccompanied',
 'OCCUPATION_TYPE_Accountants',
 'OCCUPATION_TYPE_Cleaning staff',
 'OCCUPATION_TYPE_Cooking staff',
 'OCCUPATION_TYPE_Core staff',
 'OCCUPATION_TYPE_Drivers',
 'OCCUPATION_TYPE_HR staff',
 'OCCUPATION_TYPE_High skill tech staff',
 'OCCUPATION_TYPE_IT staff',
 'OCCUPATION_TYPE_Laborers',
 'OCCUPATION_TYPE_Low-skill Laborers',
 'OCCUPATION_TYPE_Managers',
 'OCCUPATION_TYPE_Medicine staff',
 'OCCUPATION_TYPE_Private service staff',
 'OCCUPATION_TYPE_Realty agents',
 'OCCUPATION_TYPE_Sales staff',
 'OCCUPATION_TYPE_Secretaries',
 'OCCUPATION_TYPE_Security staff',
 'OCCUPATION_TYPE_Waiters/barmen staff',
 'ORGANIZATION_TYPE_Advertising',
 'ORGANIZATION_TYPE_Agriculture',
 'ORGANIZATION_TYPE_Bank',
 'ORGANIZATION_TYPE_Business Entity Type 1',
 'ORGANIZATION_TYPE_Business Entity Type 2',
 'ORGANIZATION_TYPE_Business Entity Type 3',
 'ORGANIZATION_TYPE_Cleaning',
 'ORGANIZATION_TYPE_Construction',
 'ORGANIZATION_TYPE_Culture',
 'ORGANIZATION_TYPE_Electricity',
 'ORGANIZATION_TYPE_Emergency',
 'ORGANIZATION_TYPE_Government',
 'ORGANIZATION_TYPE_Hotel',
 'ORGANIZATION_TYPE_Housing',
 'ORGANIZATION_TYPE_Industry: type 1',
 'ORGANIZATION_TYPE_Industry: type 10',
 'ORGANIZATION_TYPE_Industry: type 11',
 'ORGANIZATION_TYPE_Industry: type 12',
 'ORGANIZATION_TYPE_Industry: type 13',
 'ORGANIZATION_TYPE_Industry: type 2',
 'ORGANIZATION_TYPE_Industry: type 3',
 'ORGANIZATION_TYPE_Industry: type 4',
 'ORGANIZATION_TYPE_Industry: type 5',
 'ORGANIZATION_TYPE_Industry: type 6',
 'ORGANIZATION_TYPE_Industry: type 7',
 'ORGANIZATION_TYPE_Industry: type 8',
 'ORGANIZATION_TYPE_Industry: type 9',
 'ORGANIZATION_TYPE_Insurance',
 'ORGANIZATION_TYPE_Kindergarten',
 'ORGANIZATION_TYPE_Legal Services',
 'ORGANIZATION_TYPE_Medicine',
 'ORGANIZATION_TYPE_Military',
 'ORGANIZATION_TYPE_Mobile',
 'ORGANIZATION_TYPE_Other',
 'ORGANIZATION_TYPE_Police',
 'ORGANIZATION_TYPE_Postal',
 'ORGANIZATION_TYPE_Realtor',
 'ORGANIZATION_TYPE_Religion',
 'ORGANIZATION_TYPE_Restaurant',
 'ORGANIZATION_TYPE_School',
 'ORGANIZATION_TYPE_Security',
 'ORGANIZATION_TYPE_Security Ministries',
 'ORGANIZATION_TYPE_Self-employed',
 'ORGANIZATION_TYPE_Services',
 'ORGANIZATION_TYPE_Telecom',
 'ORGANIZATION_TYPE_Trade: type 1',
 'ORGANIZATION_TYPE_Trade: type 2',
 'ORGANIZATION_TYPE_Trade: type 3',
 'ORGANIZATION_TYPE_Trade: type 4',
 'ORGANIZATION_TYPE_Trade: type 5',
 'ORGANIZATION_TYPE_Trade: type 6',
 'ORGANIZATION_TYPE_Trade: type 7',
 'ORGANIZATION_TYPE_Transport: type 1',
 'ORGANIZATION_TYPE_Transport: type 2',
 'ORGANIZATION_TYPE_Transport: type 3',
 'ORGANIZATION_TYPE_Transport: type 4',
 'ORGANIZATION_TYPE_University',
 'ORGANIZATION_TYPE_XNA',
 'WALLSMATERIAL_MODE_Block',
 'WALLSMATERIAL_MODE_Mixed',
 'WALLSMATERIAL_MODE_Monolithic',
 'WALLSMATERIAL_MODE_Others',
 'WALLSMATERIAL_MODE_Panel',
 'WALLSMATERIAL_MODE_Stone, brick',
 'WALLSMATERIAL_MODE_Wooden',
 'WEEKDAY_APPR_PROCESS_START_FRIDAY',
 'WEEKDAY_APPR_PROCESS_START_MONDAY',
 'WEEKDAY_APPR_PROCESS_START_SATURDAY',
 'WEEKDAY_APPR_PROCESS_START_SUNDAY',
 'WEEKDAY_APPR_PROCESS_START_THURSDAY',
 'WEEKDAY_APPR_PROCESS_START_TUESDAY',
 'WEEKDAY_APPR_PROCESS_START_WEDNESDAY',
 'DAYS_EMPLOYED_PERC',
 'INCOME_CREDIT_PERC',
 'INCOME_PER_PERSON',
 'ANNUITY_INCOME_PERC',
 'PAYMENT_RATE',
 'BURO_AMT_ANNUITY_MAX',
 'BURO_AMT_ANNUITY_MEAN',
 'BURO_STATUS_1_MEAN_MEAN',
 'BURO_STATUS_3_MEAN_MEAN',
 'BURO_CREDIT_TYPE_Loan for working capital replenishment_MEAN',
 'BURO_DAYS_CREDIT_MIN',
 'BURO_DAYS_CREDIT_MAX',
 'BURO_DAYS_CREDIT_MEAN',
 'BURO_DAYS_CREDIT_VAR',
 'BURO_AMT_CREDIT_SUM_LIMIT_MEAN',
 'BURO_AMT_CREDIT_SUM_LIMIT_SUM',
 'BURO_CREDIT_ACTIVE_Active_MEAN',
 'BURO_AMT_CREDIT_SUM_MAX',
 'BURO_AMT_CREDIT_SUM_MEAN',
 'BURO_AMT_CREDIT_SUM_SUM',
 'BURO_CREDIT_TYPE_Mobile operator loan_MEAN',
 'BURO_DAYS_CREDIT_UPDATE_MEAN',
 'BURO_CREDIT_ACTIVE_Sold_MEAN',
 'BURO_STATUS_0_MEAN_MEAN',
 'BURO_CREDIT_ACTIVE_Closed_MEAN',
 'BURO_CREDIT_DAY_OVERDUE_MAX',
 'BURO_CREDIT_DAY_OVERDUE_MEAN',
 'BURO_STATUS_5_MEAN_MEAN',
 'BURO_CREDIT_TYPE_Car loan_MEAN',
 'BURO_STATUS_X_MEAN_MEAN',
 'BURO_CREDIT_TYPE_Credit card_MEAN',
 'BURO_MONTHS_BALANCE_MAX_MAX',
 'BURO_CREDIT_TYPE_Interbank credit_MEAN',
 'BURO_CREDIT_TYPE_Consumer credit_MEAN',
 'BURO_STATUS_C_MEAN_MEAN',
 'BURO_STATUS_2_MEAN_MEAN',
 'BURO_CREDIT_ACTIVE_Bad debt_MEAN',
 'BURO_CREDIT_TYPE_Real estate loan_MEAN',
 'BURO_MONTHS_BALANCE_SIZE_MEAN',
 'BURO_MONTHS_BALANCE_SIZE_SUM',
 'BURO_AMT_CREDIT_MAX_OVERDUE_MEAN',
 'BURO_CREDIT_CURRENCY_currency 1_MEAN',
 'BURO_CNT_CREDIT_PROLONG_SUM',
 'BURO_CREDIT_TYPE_Another type of loan_MEAN',
 'BURO_CREDIT_CURRENCY_currency 2_MEAN',
 'BURO_MONTHS_BALANCE_MIN_MIN',
 'BURO_CREDIT_ACTIVE_nan_MEAN',
 'BURO_CREDIT_TYPE_Loan for purchase of shares (margin lending)_MEAN',
 'BURO_DAYS_CREDIT_ENDDATE_MIN',
 'BURO_DAYS_CREDIT_ENDDATE_MAX',
 'BURO_DAYS_CREDIT_ENDDATE_MEAN',
 'BURO_AMT_CREDIT_SUM_OVERDUE_MEAN',
 'BURO_CREDIT_CURRENCY_currency 4_MEAN',
 'BURO_CREDIT_TYPE_Microloan_MEAN',
 'BURO_CREDIT_TYPE_Cash loan (non-earmarked)_MEAN',
 'BURO_CREDIT_CURRENCY_nan_MEAN',
 'BURO_CREDIT_TYPE_nan_MEAN',
 'BURO_CREDIT_TYPE_Mortgage_MEAN',
 'BURO_AMT_CREDIT_SUM_DEBT_MAX',
 'BURO_AMT_CREDIT_SUM_DEBT_MEAN',
 'BURO_AMT_CREDIT_SUM_DEBT_SUM',
 'BURO_CREDIT_TYPE_Loan for the purchase of equipment_MEAN',
 'BURO_STATUS_4_MEAN_MEAN',
 'BURO_STATUS_nan_MEAN_MEAN',
 'BURO_CREDIT_CURRENCY_currency 3_MEAN',
 'BURO_CREDIT_TYPE_Loan for business development_MEAN',
 'BURO_CREDIT_TYPE_Unknown type of loan_MEAN',
 'ACTIVE_AMT_ANNUITY_MAX',
 'ACTIVE_AMT_ANNUITY_MEAN',
 'ACTIVE_DAYS_CREDIT_UPDATE_MEAN',
 'ACTIVE_AMT_CREDIT_SUM_DEBT_MAX',
 'ACTIVE_AMT_CREDIT_SUM_DEBT_MEAN',
 'ACTIVE_AMT_CREDIT_SUM_DEBT_SUM',
 'ACTIVE_MONTHS_BALANCE_SIZE_MEAN',
 'ACTIVE_MONTHS_BALANCE_SIZE_SUM',
 'ACTIVE_DAYS_CREDIT_MIN',
 'ACTIVE_DAYS_CREDIT_MAX',
 'ACTIVE_DAYS_CREDIT_MEAN',
 'ACTIVE_DAYS_CREDIT_VAR',
 'ACTIVE_AMT_CREDIT_MAX_OVERDUE_MEAN',
 'ACTIVE_CREDIT_DAY_OVERDUE_MAX',
 'ACTIVE_CREDIT_DAY_OVERDUE_MEAN',
 'ACTIVE_CNT_CREDIT_PROLONG_SUM',
 'ACTIVE_AMT_CREDIT_SUM_LIMIT_MEAN',
 'ACTIVE_AMT_CREDIT_SUM_LIMIT_SUM',
 'ACTIVE_MONTHS_BALANCE_MIN_MIN',
 'ACTIVE_DAYS_CREDIT_ENDDATE_MIN',
 'ACTIVE_DAYS_CREDIT_ENDDATE_MAX',
 'ACTIVE_DAYS_CREDIT_ENDDATE_MEAN',
 'ACTIVE_AMT_CREDIT_SUM_OVERDUE_MEAN',
 'ACTIVE_MONTHS_BALANCE_MAX_MAX',
 'ACTIVE_AMT_CREDIT_SUM_MAX',
 'ACTIVE_AMT_CREDIT_SUM_MEAN',
 'ACTIVE_AMT_CREDIT_SUM_SUM',
 'CLOSED_AMT_ANNUITY_MAX',
 'CLOSED_AMT_ANNUITY_MEAN',
 'CLOSED_DAYS_CREDIT_UPDATE_MEAN',
 'CLOSED_AMT_CREDIT_SUM_DEBT_MAX',
 'CLOSED_AMT_CREDIT_SUM_DEBT_MEAN',
 'CLOSED_AMT_CREDIT_SUM_DEBT_SUM',
 'CLOSED_MONTHS_BALANCE_SIZE_MEAN',
 'CLOSED_MONTHS_BALANCE_SIZE_SUM',
 'CLOSED_DAYS_CREDIT_MIN',
 'CLOSED_DAYS_CREDIT_MAX',
 'CLOSED_DAYS_CREDIT_MEAN',
 'CLOSED_DAYS_CREDIT_VAR',
 'CLOSED_AMT_CREDIT_MAX_OVERDUE_MEAN',
 'CLOSED_CREDIT_DAY_OVERDUE_MAX',
 'CLOSED_CREDIT_DAY_OVERDUE_MEAN',
 'CLOSED_CNT_CREDIT_PROLONG_SUM',
 'CLOSED_AMT_CREDIT_SUM_LIMIT_MEAN',
 'CLOSED_AMT_CREDIT_SUM_LIMIT_SUM',
 'CLOSED_MONTHS_BALANCE_MIN_MIN',
 'CLOSED_DAYS_CREDIT_ENDDATE_MIN',
 'CLOSED_DAYS_CREDIT_ENDDATE_MAX',
 'CLOSED_DAYS_CREDIT_ENDDATE_MEAN',
 'CLOSED_AMT_CREDIT_SUM_OVERDUE_MEAN',
 'CLOSED_MONTHS_BALANCE_MAX_MAX',
 'CLOSED_AMT_CREDIT_SUM_MAX',
 'CLOSED_AMT_CREDIT_SUM_MEAN',
 'CLOSED_AMT_CREDIT_SUM_SUM',
 'PREV_NAME_CASH_LOAN_PURPOSE_nan_MEAN',
 'PREV_NAME_CASH_LOAN_PURPOSE_nan_SUM',
 'PREV_NAME_SELLER_INDUSTRY_MLM partners_MEAN',
 'PREV_NAME_SELLER_INDUSTRY_MLM partners_SUM',
 'PREV_CHANNEL_TYPE_Stone_MEAN',
 'PREV_CHANNEL_TYPE_Stone_SUM',
 'PREV_NAME_TYPE_SUITE_Spouse, partner_MEAN',
 'PREV_NAME_TYPE_SUITE_Spouse, partner_SUM',
 'PREV_NAME_SELLER_INDUSTRY_Auto technology_MEAN',
 'PREV_NAME_SELLER_INDUSTRY_Auto technology_SUM',
 'PREV_NAME_CASH_LOAN_PURPOSE_Money for a third person_MEAN',
 'PREV_NAME_CASH_LOAN_PURPOSE_Money for a third person_SUM',
 'PREV_NAME_GOODS_CATEGORY_Homewares_MEAN',
 'PREV_NAME_GOODS_CATEGORY_Homewares_SUM',
 'PREV_NAME_CASH_LOAN_PURPOSE_Urgent needs_MEAN',
 'PREV_NAME_CASH_LOAN_PURPOSE_Urgent needs_SUM',
 'PREV_NAME_SELLER_INDUSTRY_XNA_MEAN',
 'PREV_NAME_SELLER_INDUSTRY_XNA_SUM',
 'PREV_NAME_GOODS_CATEGORY_Additional Service_MEAN',
 'PREV_NAME_GOODS_CATEGORY_Additional Service_SUM',
 'PREV_CODE_REJECT_REASON_SCOFR_MEAN',
 'PREV_CODE_REJECT_REASON_SCOFR_SUM',
 'PREV_PRODUCT_COMBINATION_Card Street_MEAN',
 'PREV_PRODUCT_COMBINATION_Card Street_SUM',
 'PREV_NAME_CONTRACT_TYPE_Consumer loans_MEAN',
 'PREV_NAME_CONTRACT_TYPE_Consumer loans_SUM',
 'PREV_WEEKDAY_APPR_PROCESS_START_SATURDAY_MEAN',
 'PREV_WEEKDAY_APPR_PROCESS_START_SATURDAY_SUM',
 'PREV_PRODUCT_COMBINATION_POS other with interest_MEAN',
 'PREV_PRODUCT_COMBINATION_POS other with interest_SUM',
 'PREV_NAME_GOODS_CATEGORY_Medicine_MEAN',
 'PREV_NAME_GOODS_CATEGORY_Medicine_SUM',
 'PREV_DAYS_DECISION_MIN',
 'PREV_DAYS_DECISION_MAX',
 'PREV_DAYS_DECISION_MEAN',
 'PREV_NAME_CONTRACT_STATUS_Refused_MEAN',
 'PREV_NAME_CONTRACT_STATUS_Refused_SUM',
 'PREV_PRODUCT_COMBINATION_POS others without interest_MEAN',
 'PREV_PRODUCT_COMBINATION_POS others without interest_SUM',
 'PREV_CHANNEL_TYPE_Country-wide_MEAN',
 'PREV_CHANNEL_TYPE_Country-wide_SUM',
 'PREV_CHANNEL_TYPE_Car dealer_MEAN',
 'PREV_CHANNEL_TYPE_Car dealer_SUM',
 'PREV_NAME_GOODS_CATEGORY_Animals_MEAN',
 'PREV_NAME_GOODS_CATEGORY_Animals_SUM',
 'PREV_NAME_YIELD_GROUP_middle_MEAN',
 'PREV_NAME_YIELD_GROUP_middle_SUM',
 'PREV_WEEKDAY_APPR_PROCESS_START_MONDAY_MEAN',
 'PREV_WEEKDAY_APPR_PROCESS_START_MONDAY_SUM',
 'PREV_RATE_DOWN_PAYMENT_MIN',
 'PREV_RATE_DOWN_PAYMENT_MAX',
 'PREV_RATE_DOWN_PAYMENT_MEAN',
 'PREV_NAME_SELLER_INDUSTRY_Construction_MEAN',
 'PREV_NAME_SELLER_INDUSTRY_Construction_SUM',
 'PREV_NAME_CASH_LOAN_PURPOSE_Repairs_MEAN',
 'PREV_NAME_CASH_LOAN_PURPOSE_Repairs_SUM',
 'PREV_NAME_CLIENT_TYPE_nan_MEAN',
 'PREV_NAME_CLIENT_TYPE_nan_SUM',
 'PREV_CODE_REJECT_REASON_CLIENT_MEAN',
 'PREV_CODE_REJECT_REASON_CLIENT_SUM',
 'PREV_NAME_CLIENT_TYPE_Repeater_MEAN',
 'PREV_NAME_CLIENT_TYPE_Repeater_SUM',
 'PREV_NAME_CLIENT_TYPE_New_MEAN',
 'PREV_NAME_CLIENT_TYPE_New_SUM',
 'PREV_NAME_GOODS_CATEGORY_Furniture_MEAN',
 'PREV_NAME_GOODS_CATEGORY_Furniture_SUM',
 'PREV_NAME_GOODS_CATEGORY_Office Appliances_MEAN',
 'PREV_NAME_GOODS_CATEGORY_Office Appliances_SUM',
 'PREV_CODE_REJECT_REASON_SCO_MEAN',
 'PREV_CODE_REJECT_REASON_SCO_SUM',
 'PREV_NAME_PORTFOLIO_Cash_MEAN',
 'PREV_NAME_PORTFOLIO_Cash_SUM',
 'PREV_NAME_TYPE_SUITE_Other_A_MEAN',
 'PREV_NAME_TYPE_SUITE_Other_A_SUM',
 'PREV_NAME_CASH_LOAN_PURPOSE_Wedding / gift / holiday_MEAN',
 'PREV_NAME_CASH_LOAN_PURPOSE_Wedding / gift / holiday_SUM',
 'PREV_NAME_GOODS_CATEGORY_Clothing and Accessories_MEAN',
 'PREV_NAME_GOODS_CATEGORY_Clothing and Accessories_SUM',
 'PREV_NAME_CONTRACT_STATUS_Canceled_MEAN',
 'PREV_NAME_CONTRACT_STATUS_Canceled_SUM',
 'PREV_NAME_GOODS_CATEGORY_Audio/Video_MEAN',
 'PREV_NAME_GOODS_CATEGORY_Audio/Video_SUM',
 'PREV_NAME_GOODS_CATEGORY_Consumer Electronics_MEAN',
 'PREV_NAME_GOODS_CATEGORY_Consumer Electronics_SUM',
 'PREV_WEEKDAY_APPR_PROCESS_START_TUESDAY_MEAN',
 'PREV_WEEKDAY_APPR_PROCESS_START_TUESDAY_SUM',
 'PREV_NAME_GOODS_CATEGORY_Insurance_MEAN',
 'PREV_NAME_GOODS_CATEGORY_Insurance_SUM',
 'PREV_NAME_PAYMENT_TYPE_XNA_MEAN',
 'PREV_NAME_PAYMENT_TYPE_XNA_SUM',
 'PREV_AMT_ANNUITY_MIN',
 'PREV_AMT_ANNUITY_MAX',
 'PREV_AMT_ANNUITY_MEAN',
 'PREV_PRODUCT_COMBINATION_Cash X-Sell: low_MEAN',
 'PREV_PRODUCT_COMBINATION_Cash X-Sell: low_SUM',
 'PREV_NAME_SELLER_INDUSTRY_Industry_MEAN',
 'PREV_NAME_SELLER_INDUSTRY_Industry_SUM',
 'PREV_NAME_PRODUCT_TYPE_walk-in_MEAN',
 'PREV_NAME_PRODUCT_TYPE_walk-in_SUM',
 'PREV_NAME_GOODS_CATEGORY_Direct Sales_MEAN',
 'PREV_NAME_GOODS_CATEGORY_Direct Sales_SUM',
 'PREV_NAME_CASH_LOAN_PURPOSE_Refusal to name the goal_MEAN',
 'PREV_NAME_CASH_LOAN_PURPOSE_Refusal to name the goal_SUM',
 'PREV_WEEKDAY_APPR_PROCESS_START_WEDNESDAY_MEAN',
 'PREV_WEEKDAY_APPR_PROCESS_START_WEDNESDAY_SUM',
 'PREV_NAME_PRODUCT_TYPE_XNA_MEAN',
 'PREV_NAME_PRODUCT_TYPE_XNA_SUM',
 'PREV_NAME_GOODS_CATEGORY_nan_MEAN',
 'PREV_NAME_GOODS_CATEGORY_nan_SUM',
 'PREV_NAME_GOODS_CATEGORY_Jewelry_MEAN',
 'PREV_NAME_GOODS_CATEGORY_Jewelry_SUM',
 'PREV_NAME_CONTRACT_STATUS_Approved_MEAN',
 'PREV_NAME_CONTRACT_STATUS_Approved_SUM',
 'PREV_NAME_GOODS_CATEGORY_Gardening_MEAN',
 'PREV_NAME_GOODS_CATEGORY_Gardening_SUM',
 'PREV_NAME_TYPE_SUITE_Group of people_MEAN',
 'PREV_NAME_TYPE_SUITE_Group of people_SUM',
 'PREV_NAME_PORTFOLIO_XNA_MEAN',
 'PREV_NAME_PORTFOLIO_XNA_SUM',
 'PREV_NAME_CASH_LOAN_PURPOSE_Everyday expenses_MEAN',
 'PREV_NAME_CASH_LOAN_PURPOSE_Everyday expenses_SUM',
 'PREV_NAME_TYPE_SUITE_Other_B_MEAN',
 'PREV_NAME_TYPE_SUITE_Other_B_SUM',
 'PREV_PRODUCT_COMBINATION_Cash Street: middle_MEAN',
 'PREV_PRODUCT_COMBINATION_Cash Street: middle_SUM',
 'PREV_WEEKDAY_APPR_PROCESS_START_nan_MEAN',
 'PREV_WEEKDAY_APPR_PROCESS_START_nan_SUM',
 'PREV_NAME_CASH_LOAN_PURPOSE_Buying a used car_MEAN',
 'PREV_NAME_CASH_LOAN_PURPOSE_Buying a used car_SUM',
 'PREV_CODE_REJECT_REASON_XAP_MEAN',
 'PREV_CODE_REJECT_REASON_XAP_SUM',
 'PREV_NAME_GOODS_CATEGORY_Vehicles_MEAN',
 'PREV_NAME_GOODS_CATEGORY_Vehicles_SUM',
 'PREV_PRODUCT_COMBINATION_POS household without interest_MEAN',
 'PREV_PRODUCT_COMBINATION_POS household without interest_SUM',
 'PREV_AMT_CREDIT_MIN',
 'PREV_AMT_CREDIT_MAX',
 'PREV_AMT_CREDIT_MEAN',
 'PREV_NAME_TYPE_SUITE_Unaccompanied_MEAN',
 'PREV_NAME_TYPE_SUITE_Unaccompanied_SUM',
 'PREV_CHANNEL_TYPE_Contact center_MEAN',
 'PREV_CHANNEL_TYPE_Contact center_SUM',
 'PREV_NAME_GOODS_CATEGORY_Fitness_MEAN',
 'PREV_NAME_GOODS_CATEGORY_Fitness_SUM',
 'PREV_NAME_GOODS_CATEGORY_Mobile_MEAN',
 'PREV_NAME_GOODS_CATEGORY_Mobile_SUM',
 'PREV_CHANNEL_TYPE_AP+ (Cash loan)_MEAN',
 'PREV_CHANNEL_TYPE_AP+ (Cash loan)_SUM',
 'PREV_NAME_CLIENT_TYPE_XNA_MEAN',
 'PREV_NAME_CLIENT_TYPE_XNA_SUM',
 'PREV_NAME_YIELD_GROUP_XNA_MEAN',
 'PREV_NAME_YIELD_GROUP_XNA_SUM',
 'PREV_PRODUCT_COMBINATION_POS mobile without interest_MEAN',
 'PREV_PRODUCT_COMBINATION_POS mobile without interest_SUM',
 'PREV_CODE_REJECT_REASON_HC_MEAN',
 'PREV_CODE_REJECT_REASON_HC_SUM',
 'PREV_PRODUCT_COMBINATION_Cash X-Sell: high_MEAN',
 'PREV_PRODUCT_COMBINATION_Cash X-Sell: high_SUM',
 'PREV_NAME_PAYMENT_TYPE_Cashless from the account of the employer_MEAN',
 'PREV_NAME_PAYMENT_TYPE_Cashless from the account of the employer_SUM',
 'PREV_NAME_SELLER_INDUSTRY_nan_MEAN',
 'PREV_NAME_SELLER_INDUSTRY_nan_SUM',
 'PREV_PRODUCT_COMBINATION_Cash Street: high_MEAN',
 'PREV_PRODUCT_COMBINATION_Cash Street: high_SUM',
 'PREV_NAME_CASH_LOAN_PURPOSE_Journey_MEAN',
 'PREV_NAME_CASH_LOAN_PURPOSE_Journey_SUM',
 'PREV_CHANNEL_TYPE_Channel of corporate sales_MEAN',
 'PREV_CHANNEL_TYPE_Channel of corporate sales_SUM',
 'PREV_CHANNEL_TYPE_Regional / Local_MEAN',
 'PREV_CHANNEL_TYPE_Regional / Local_SUM',
 'PREV_NAME_GOODS_CATEGORY_Auto Accessories_MEAN',
 'PREV_NAME_GOODS_CATEGORY_Auto Accessories_SUM',
 'PREV_NAME_YIELD_GROUP_low_normal_MEAN',
 'PREV_NAME_YIELD_GROUP_low_normal_SUM',
 'PREV_NAME_TYPE_SUITE_nan_MEAN',
 'PREV_NAME_TYPE_SUITE_nan_SUM',
 'PREV_NAME_PORTFOLIO_nan_MEAN',
 'PREV_NAME_PORTFOLIO_nan_SUM',
 'PREV_NAME_SELLER_INDUSTRY_Tourism_MEAN',
 'PREV_NAME_SELLER_INDUSTRY_Tourism_SUM',
 'PREV_NAME_CASH_LOAN_PURPOSE_Purchase of electronic equipment_MEAN',
 'PREV_NAME_CASH_LOAN_PURPOSE_Purchase of electronic equipment_SUM',
 'PREV_PRODUCT_COMBINATION_nan_MEAN',
 'PREV_PRODUCT_COMBINATION_nan_SUM',
 'PREV_NAME_CASH_LOAN_PURPOSE_Buying a garage_MEAN',
 'PREV_NAME_CASH_LOAN_PURPOSE_Buying a garage_SUM',
 'PREV_NAME_CONTRACT_TYPE_XNA_MEAN',
 'PREV_NAME_CONTRACT_TYPE_XNA_SUM',
 'PREV_NAME_CASH_LOAN_PURPOSE_XNA_MEAN',
 'PREV_NAME_CASH_LOAN_PURPOSE_XNA_SUM',
 'PREV_NAME_CASH_LOAN_PURPOSE_Payments on other loans_MEAN',
 'PREV_NAME_CASH_LOAN_PURPOSE_Payments on other loans_SUM',
 'PREV_NAME_PAYMENT_TYPE_Non-cash from your account_MEAN',
 'PREV_NAME_PAYMENT_TYPE_Non-cash from your account_SUM',
 'PREV_NAME_TYPE_SUITE_Children_MEAN',
 'PREV_NAME_TYPE_SUITE_Children_SUM',
 'PREV_NAME_GOODS_CATEGORY_Computers_MEAN',
 'PREV_NAME_GOODS_CATEGORY_Computers_SUM',
 'PREV_NAME_CASH_LOAN_PURPOSE_Medicine_MEAN',
 'PREV_NAME_CASH_LOAN_PURPOSE_Medicine_SUM',
 'PREV_NAME_CONTRACT_TYPE_Cash loans_MEAN',
 'PREV_NAME_CONTRACT_TYPE_Cash loans_SUM',
 'PREV_NAME_GOODS_CATEGORY_Education_MEAN',
 'PREV_NAME_GOODS_CATEGORY_Education_SUM',
 'PREV_NAME_CASH_LOAN_PURPOSE_Other_MEAN',
 'PREV_NAME_CASH_LOAN_PURPOSE_Other_SUM',
 'PREV_NAME_CASH_LOAN_PURPOSE_Buying a holiday home / land_MEAN',
 'PREV_NAME_CASH_LOAN_PURPOSE_Buying a holiday home / land_SUM',

In [10]:
train_df = df[df['TARGET'].notnull()]
test_df = df[df['TARGET'].isnull()].drop(columns = ['TARGET'])
print(train_df.shape, test_df.shape)

(307511, 1037) (48744, 1036)

In [12]:
train_df.to_csv('./preprocessed_data/train_v2.csv', index = False)
test_df.to_csv('./preprocessed_data/test_v2.csv', index = False)

In [13]:
del df, features_top, train_df, test_df
gc.collect()

178

In [3]:
train = pd.read_csv('./preprocessed_data/train_v2.csv')
test = pd.read_csv('./preprocessed_data/test_v2.csv')

In [4]:
submission, fi, metrics, valid_df = lgb_model(train, test)

Training Data Shape:  (307511, 1035)
Testing Data Shape:  (48744, 1035)
Training until validation scores don't improve for 100 rounds.
[200]	valid's auc: 0.775513	train's auc: 0.802874
[400]	valid's auc: 0.785078	train's auc: 0.829865
[600]	valid's auc: 0.787897	train's auc: 0.848137
[800]	valid's auc: 0.788559	train's auc: 0.863446
[1000]	valid's auc: 0.788639	train's auc: 0.876371
Early stopping, best iteration is:
[946]	valid's auc: 0.788694	train's auc: 0.873034
Training until validation scores don't improve for 100 rounds.
[200]	valid's auc: 0.778292	train's auc: 0.801761
[400]	valid's auc: 0.789323	train's auc: 0.828652
[600]	valid's auc: 0.792869	train's auc: 0.847172
[800]	valid's auc: 0.794409	train's auc: 0.862551
[1000]	valid's auc: 0.794781	train's auc: 0.875802
[1200]	valid's auc: 0.794956	train's auc: 0.887113
Early stopping, best iteration is:
[1168]	valid's auc: 0.795045	train's auc: 0.885562
Training until validation scores don't improve for 100 rounds.
[200]	valid's auc: 0.768278	train's auc: 0.803491
[400]	valid's auc: 0.779728	train's auc: 0.830122
[600]	valid's auc: 0.783312	train's auc: 0.848587
[800]	valid's auc: 0.784848	train's auc: 0.863823
[1000]	valid's auc: 0.785331	train's auc: 0.877081
[1200]	valid's auc: 0.785492	train's auc: 0.888849
Early stopping, best iteration is:
[1229]	valid's auc: 0.785596	train's auc: 0.890422
Training until validation scores don't improve for 100 rounds.
[200]	valid's auc: 0.776863	train's auc: 0.802235
[400]	valid's auc: 0.786955	train's auc: 0.829151
[600]	valid's auc: 0.789895	train's auc: 0.847774
[800]	valid's auc: 0.790836	train's auc: 0.863299
[1000]	valid's auc: 0.79141	train's auc: 0.876358
Early stopping, best iteration is:
[1009]	valid's auc: 0.791424	train's auc: 0.876893
Training until validation scores don't improve for 100 rounds.
[200]	valid's auc: 0.77684	train's auc: 0.802227
[400]	valid's auc: 0.787232	train's auc: 0.828688
[600]	valid's auc: 0.790823	train's auc: 0.847067
[800]	valid's auc: 0.792143	train's auc: 0.862671
[1000]	valid's auc: 0.79268	train's auc: 0.875629
[1200]	valid's auc: 0.793024	train's auc: 0.887353
Early stopping, best iteration is:
[1209]	valid's auc: 0.793054	train's auc: 0.887846

In [5]:
valid_df.to_csv('./model_performance/valid_v2.csv',index=False)

In [6]:
metrics

      fold     train     valid
0        0  0.873034  0.788694
1        1  0.885562  0.795045
2        2  0.890422  0.785596
3        3  0.876893  0.791424
4        4  0.887846  0.793054
5  overall  0.882751  0.790694

In [7]:
submission.to_csv('./model_performance/v2_pred_0.79.csv',index=False)